export {
  addVec,
  distance,
  rectBottom,
  rectContains,
  rectRight,
  rectsOverlap,
  segmentIntersectsRect,
  nearestPointOnPolyline,
  nearestPointOnSegment,
  normalXY,
  polylineLength,
  roundVec,
  scaleVec,
  subVec,
  vec3,
  vecEquals,
  vecLength,
  type NearestPoint,
  type Polyline,
  type Rect,
  type Vec3,
} from './geometry.js';

export {
  BLOCK_PITCH_MM,
  BLOCK_TERMINAL_Z_MM,
  BOARD_DEPTH_MM,
  BOARD_HEIGHT_MM,
  BOARD_WIDTH_MM,
  BoardError,
  BODY_TERMINAL_Z_MM,
  boardTerminalPos,
  CHANNEL_LANE_DIRECTION,
  circledNumber,
  findBoardTerminal,
  HARNESS_APPROACH_MM,
  HARNESS_PITCH_MM,
  JIPM_BOARD,
  loadBoard,
  PANEL_HOLE_OFFSET_MM,
  pinRole,
  resolveEndpoint,
  roleLabel,
  SOCKET_BODY_LENGTH_MM,
  SOCKET_BODY_WIDTH_MM,
  SOCKET_COL_PITCH_MM,
  SOCKET_IDS,
  SOCKET_PIN_GRID,
  SOCKET_PIN_HOLE_COL_PITCH_MM,
  SOCKET_PIN_HOLE_ROW_PITCH_MM,
  SOCKET_PITCH_MM,
  SOCKET_SLOT_INSET_MM,
  SOCKET_TERMINAL_Z_MM,
  SOCKET_TIER_INSET_MM,
  SOCKET_TIER_ROW_PITCH_MM,
  socketBodyRect,
  socketPinHoleOffsets,
  socketPinOffset,
  socketPinTerminal,
  socketRowExit,
  SUPPLY_TERMINAL_COUNT,
  TERMINAL_PICK_RADIUS_MM,
  WIRE_RUN_Z_MM,
  type BoardDefinition,
  type BoardEndpoint,
  type BoardTerminal,
  type ConsoleShape,
  type FixedLink,
  type FixedWire,
  type Footprint,
  type LampDefinition,
  type PushButtonColor,
  type PushButtonDefinition,
  type SocketDefinition,
  type SocketId,
  type TerminalRole,
  type WiringChannel,
} from './board-jipm.js';

export {
  CHECK_SOCKET_ROLE,
  DEFAULT_SOCKET_ROLES,
  hasRole,
  isSocketId,
  isSocketRole,
  roleOf,
  RoleError,
  socketOf,
  socketPartId,
  TASK1_SOCKET_ROLES,
  TASK2_SOCKET_ROLES,
  terminalIdFor,
  toNetlistTerminal,
  toPhysicalTerminal,
  validateSocketRoles,
  type SocketRole,
  type SocketRoles,
} from './roles.js';

export {
  catalogEntry,
  CatalogError,
  DEFAULT_INVENTORY,
  DEFAULT_TIMER_PRESET_MS,
  DEFAULT_TIMER_RANGE,
  findTimerRange,
  inventoryCount,
  isMountableKind,
  PART_CATALOG,
  remainingInventory,
  snapPresetToStep,
  TIMER_RANGES,
  type CatalogEntry,
  type InventoryItem,
  type MountableKind,
  type TimerRange,
} from './catalog.js';
