export {
  addVec,
  distance,
  rectBottom,
  rectContains,
  rectRight,
  rectsOverlap,
  segmentIntersectsRect,
  nearestPointOnPolyline,
  nearestPointOnSegment,
  normalXY,
  polylineLength,
  roundVec,
  scaleVec,
  subVec,
  vec3,
  vecEquals,
  vecLength,
  type NearestPoint,
  type Polyline,
  type Rect,
  type Vec3,
} from './geometry.js';

export {
  BLOCK_PITCH_MM,
  BLOCK_TERMINAL_Z_MM,
  BOARD_DEPTH_MM,
  BOARD_HEIGHT_MM,
  BOARD_WIDTH_MM,
  BoardError,
  BODY_TERMINAL_PICK_RADIUS_MM,
  BODY_TERMINAL_Z_MM,
  boardTerminalPos,
  channelBandRect,
  CHANNEL_LANE_COUNT,
  CHANNEL_LANE_DIRECTION,
  CHANNEL_LANE_PITCH_MM,
  CHECK_SOCKET_ID,
  circledNumber,
  findBoardTerminal,
  HARNESS_APPROACH_MM,
  HARNESS_PITCH_MM,
  isOffBoardTerminal,
  JIPM_BOARD,
  loadBoard,
  OUTLET_ID,
  PANEL_HOLE_OFFSET_MM,
  pinRole,
  PLC_PART_ID,
  resolveEndpoint,
  roleLabel,
  runZ,
  SOCKET_BODY_LENGTH_MM,
  SOCKET_BODY_WIDTH_MM,
  SOCKET_COL_PITCH_MM,
  SOCKET_IDS,
  SOCKET_PIN_COUNT,
  SOCKET_PIN_GRID,
  SOCKET_PIN_HOLE_COL_PITCH_MM,
  SOCKET_PIN_HOLE_ROW_PITCH_MM,
  SOCKET_PITCH_MM,
  SOCKET_SLOT_INSET_MM,
  SOCKET_TERMINAL_Z_MM,
  SOCKET_TIER_INSET_MM,
  SOCKET_TIER_ROW_PITCH_MM,
  socketBodyRect,
  socketPinHoleOffsets,
  socketPinOffset,
  socketPinTerminal,
  socketRowExit,
  SUPPLY_TERMINAL_COUNT,
  TERMINAL_PICK_RADIUS_MM,
  validateBoard,
  WIRE_LAYER_COUNT,
  WIRE_LAYER_STEP_MM,
  WIRE_RUN_X_Z_MM,
  WIRE_RUN_Y_Z_MM,
  WIRE_Z_LADDER_MM,
  type BoardDefinition,
  type BoardEndpoint,
  type BoardTerminal,
  type ConsoleShape,
  type FaceRect,
  type FixedLink,
  type FixedWire,
  type Footprint,
  type LampDefinition,
  type PlcAppearance,
  type PlcCoverMark,
  type PlcFeatureMark,
  type PlcLedMark,
  type PlcModuleDefinition,
  type PlcUnitDefinition,
  type PushButtonColor,
  type PushButtonDefinition,
  type SocketDefinition,
  type SocketId,
  type TerminalRole,
  type WiringChannel,
} from './board-jipm.js';

export {
  channelNames,
  commonOf,
  coverOpenReachMm,
  coverOpenRiseMm,
  CP1E_APPEARANCE,
  CP1E_COMMON_SIZES,
  CP1E_INPUT_OHMS_HIGH,
  CP1E_INPUT_OHMS_LOW,
  CP1E_SPEC,
  FX5U_APPEARANCE,
  FX5U_INPUT_OHMS,
  FX5U_OFF_AMPS,
  FX5U_ON_AMPS,
  FX5U_POINTS_PER_COMMON,
  FX5U_SPEC,
  groupNames,
  hexNames,
  JW300_INPUT_OHMS,
  JW300_SPEC,
  ledRow,
  octalNames,
  OUTLET_ORIGIN_MM,
  OUTLET_TERMINALS,
  PC10G_INPUT_OHMS,
  PC10G_OUTPUT_BASE,
  PC10G_SPEC,
  PLC_COVER_OPEN_DEG,
  PLC_COVER_OPEN_RAD,
  PLC_LED_AMBER,
  PLC_LED_GREEN,
  PLC_LED_OFF,
  PLC_LED_RED,
  PLC_ORIGIN_MM,
  PLC_ROW_GAP_MM,
  PLC_STAGGER_MM,
  PLC_TERMINAL_PITCH_MM,
  PLC_UNIT_CP1E,
  PLC_UNIT_FX5U,
  PLC_UNIT_JW300,
  PLC_UNIT_PC10G,
  PLC_UNITS,
  plcCoverAt,
  plcFaces,
  plcRole,
  plcUnitFor,
  RACK_BASE_HEIGHT_MM,
  RACK_BASE_MARGIN_MM,
  RACK_MODULE_HEIGHT_MM,
  RACK_MODULE_WIDTH_MM,
  RACK_POINTS_PER_COMMON,
  RACK_RAIL_HEIGHT_MM,
  RACK_TERMINAL_COLS_MM,
  RACK_TERMINAL_ROW_PITCH_MM,
  RACK_TERMINAL_TOP_MM,
  RACK_TERMINALS_PER_MODULE,
  rackModulePos,
  rackSizeMm,
  rackTerminals,
  withPlcUnit,
  type PlcFacePlacement,
} from './plc-unit.js';

export {
  BOARD_EXIT_LAYER_COUNT,
  BOARD_EXIT_Z_LADDER_MM,
  BOARD_RUN_X_Z_MM,
  BOARD_RUN_Y_Z_MM,
  boardExitRunZ,
  DESK_CORNER_RADIUS_MM,
  DESK_LANE_PITCH_MM,
  DESK_LAYER_COUNT,
  DESK_LIP_X_MM,
  DESK_MID_GAP_MM,
  DESK_MIN_CLEARANCE_MM,
  DESK_OUTLET_GAP_MM,
  DESK_ROW_GAP_MM,
  DESK_ROW_LANE_MAX,
  DESK_RUN_X_Z_MM,
  DESK_RUN_Y_Z_MM,
  DESK_SCREW_APPROACH_MM,
  DESK_SCREW_MERGE_MM,
  DESK_SCREW_STAGGER_MM,
  DESK_TRUNK_GAP_MM,
  DESK_Z_LADDER_MM,
  deskDucts,
  deskObstacles,
  deskRouteIssues,
  deskRoutes,
  deskRowLaneCount,
  deskRunZ,
  deskTrunkLaneCount,
  leadOutStaggerMm,
  screwStaggerMm,
  type DeskDuct,
  type DeskLaneSlot,
  type DeskObstacle,
  type DeskRoute,
} from './desk-routing.js';

export {
  CHECK_SOCKET_ROLE,
  DEFAULT_SOCKET_ROLES,
  hasRole,
  isSocketId,
  isSocketRole,
  roleOf,
  RoleError,
  SOCKET_ROLES,
  socketOf,
  socketPartId,
  TASK1_SOCKET_ROLES,
  TASK2_SOCKET_ROLES,
  terminalIdFor,
  toNetlistTerminal,
  toPhysicalTerminal,
  trySocketOf,
  validateSocketRoles,
  type SocketRole,
  type SocketRoles,
} from './roles.js';

export {
  catalogEntry,
  CatalogError,
  DEFAULT_INVENTORY,
  DEFAULT_TIMER_PRESET_MS,
  DEFAULT_TIMER_RANGE,
  findTimerRange,
  inventoryCount,
  isMountableKind,
  MOUNTABLE_KINDS,
  PART_CATALOG,
  remainingInventory,
  snapPresetToStep,
  TIMER_RANGE_10S,
  TIMER_RANGE_60S,
  TIMER_RANGES,
  type CatalogEntry,
  type InventoryItem,
  type MountableKind,
  type TimerRange,
} from './catalog.js';

export {
  addWire,
  checkWirableTerminal,
  createSession,
  DEFAULT_ALLOWED_COLORS,
  fail,
  failWith,
  mountedKinds,
  ok,
  plug,
  removeWire,
  SessionError,
  setPreset,
  toSessionTerminal,
  unplug,
  wireCountAtTerminal,
  wiresAt,
  type BoardSession,
  type MountedPart,
  type Result,
  type SessionErrorCode,
  type SessionOptions,
} from './session.js';

export {
  BUZZER_ID,
  createEmptySocketPart,
  createTerminalOnlyPart,
  netlistIssues,
  N_RAIL_ID,
  P_RAIL_ID,
  PB_BLOCK_ID,
  PL_BLOCK_ID,
  POWER_SUPPLY_ID,
  toNetlist,
} from './to-netlist.js';

export {
  channelsClearOfFootprints,
  crossesFootprint,
  crossingFootprint,
  deskWires,
  DIRECT_JOG_MM,
  entryChannelFor,
  filletCorners,
  isManhattan,
  LEAD_OUT_STAGGER_MM,
  MAX_DIRECT_JOG_LEVELS,
  pickLane,
  routeFixedLinks,
  routeSession,
  routeWire,
  RoutingError,
  WIRE_DIAMETER_MM,
  WIRE_FILLET_RADIUS_MM,
  WIRE_FILLET_SEGMENTS,
  type ChannelLane,
  type ChannelSpan,
  type DeskWire,
  type LaneAssignment,
  type RoutableWire,
  type RouteOptions,
  type RoutingErrorReason,
  type WireRoute,
  type WireRouteKind,
} from './routing.js';
