export {
  at,
  BUS_N,
  BUS_P,
  buzzer,
  coil,
  crA,
  crB,
  createDocument,
  DEVICE_PATTERNS,
  documentDevices,
  isContactCell,
  isLoadCell,
  lamp,
  nodeKey,
  pbA,
  pbB,
  resolveNode,
  rung,
  rungNodeCount,
  SCHEMATIC_FORMAT_VERSION,
  tA,
  tB,
  validateDocument,
  type CellKind,
  type ContactCellKind,
  type DocumentError,
  type LoadCellKind,
  type ResolvedNode,
  type Rung,
  type RungEnd,
  type SchematicCell,
  type SchematicDocument,
} from './document.js';

export {
  assignToBoard,
  CONTACT_PINS,
  deriveSocketRoles,
  requiredRoles,
  type AssignError,
  type AssignOptions,
  type Assignment,
  type AssignResult,
  type CellAssignment,
  type ContactPins,
  type PartAssignment,
  type WireSpec,
} from './assign.js';

export { toSession, type ToSessionOptions, type ToSessionResult } from './to-session.js';

export {
  contactShapes,
  DEFAULT_LAYOUT_OPTIONS,
  LAMP_FILL,
  layout,
  loadShapes,
  rungStartX,
  slotRects,
  SYMBOL_METRICS,
  terminalMarks,
  type LayoutOptions,
  type SchematicLayout,
  type Shape,
  type ShapeRole,
  type ShapeSource,
  type SlotRect,
  type TerminalMark,
} from './layout.js';

export {
  applyEdit,
  CELL_KIND_LABELS,
  DEFAULT_EDIT_PRESET_MS,
  EDIT_FORMAT_VERSION,
  editLabel,
  emptySchematic,
  MAX_CELLS_PER_RUNG,
  MAX_RUNGS,
  nextCellId,
  nextRungId,
  rungHasLoad,
  type CellDraft,
  type EditOutcome,
  type SchematicEdit,
} from './edit.js';
