export {
  IdError,
  parseTerminalId,
  partId,
  terminalId,
  terminalOwner,
  toTerminalId,
  wireId,
  type PartId,
  type TerminalId,
  type WireId,
} from './ids.js';

export {
  BUZZER_OHMS,
  CLOSED_CONTACT_OHMS,
  COIL_OHMS,
  contactOhms,
  DEFAULT_CONTACT_RESISTIVE_OHMS,
  DEFAULT_LAYER_SHORT_RATIO,
  DROPOUT_VOLTS,
  isContactClosed,
  LAMP_DIM_VOLTS,
  LAMP_LIT_VOLTS,
  LAMP_OHMS,
  loadOhms,
  MAX_LAYER_SHORT_RATIO,
  MIN_LAYER_SHORT_RATIO,
  PICKUP_VOLTS,
  PLC_INPUT_OHMS,
  PROTECTION_AMPS,
  SOURCE_INTERNAL_OHMS,
  SOURCE_VOLTS,
  TICK_MS,
  type ContactDriver,
  type ContactElement,
  type ContactFault,
  type ContactKind,
  type Element,
  type LinkElement,
  type LoadElement,
  type LoadFault,
  type LoadKind,
  type SourceElement,
} from './elements.js';

export {
  clampPreset,
  createBuzzer,
  createLamp,
  createPowerSupply,
  createPushButton,
  createRelay4c,
  createTerminalBlockLink,
  createTimer4c,
  SOCKET_COIL_MINUS_PIN,
  SOCKET_COIL_PLUS_PIN,
  SOCKET_CONTACT_PINS,
  TIMER_MIN_PRESET_MS,
  TIMER_RANGE_10S_MS,
  TIMER_RANGE_60S_MS,
  TIMER_RESET_GAP_MS,
  type LampColor,
  type Part,
  type PartKind,
  type PartMeta,
  type PlcInputChannel,
  type PlcOutputChannel,
} from './parts.js';

export {
  createPlcUnit,
  PLC_INPUT_OFF_AMPS,
  PLC_INPUT_ON_AMPS,
  plcMetaOf,
  PlcUnitError,
  type PlcOutputSpec,
  type PlcUnitSpec,
} from './plc.js';

export {
  addWire,
  allElements,
  buildNets,
  canAddWire,
  cloneNetlist,
  createNetlist,
  createWire,
  exceedsWireLimit,
  findElement,
  findPart,
  findWire,
  knownTerminals,
  MAX_WIRES_PER_TERMINAL,
  NetlistError,
  removeWire,
  resetNetlist,
  validateNetlist,
  wireCountAt,
  type Netlist,
  type NetlistIssue,
  type Nets,
  type Wire,
  type WireColor,
} from './netlist.js';

export {
  LEAK_SIEMENS,
  MAX_NODES,
  solve,
  voltageAt,
  type SolveOptions,
  type SolveResult,
} from './solver.js';

export {
  applyPowerAction,
  isPowerOn,
  RESET_SEQUENCE,
  setButtonPressed,
  type PowerActionResult,
  type PowerDevice,
  type PowerSwitches,
} from './actuators.js';

export {
  CHATTER_MIN_TRANSITIONS,
  CHATTER_WINDOW_MS,
  EventBus,
  HAZARD_KINDS,
  type ChatterEvent,
  type EventListener,
  type HazardEvent,
  type HazardKind,
  type SimEvent,
} from './events.js';

export { LOG_DECIMALS, roundSignal, SignalLog, type LogEntry, type SignalValue } from './log.js';

export {
  LAMP_LEVEL_CODE,
  Simulation,
  SimulationError,
  type LampLevel,
  type LampRuntime,
  type RelayRuntime,
  type SimulationOptions,
  type SimulationState,
  type TimerRuntime,
} from './simulation.js';

export {
  clearFaults,
  FaultError,
  injectFault,
  type FaultKind,
  type FaultTarget,
} from './faults.js';

export {
  continuity,
  CONTINUITY_OHMS,
  equivalentResistance,
  LIVE_OHM_VOLTS,
  measureAcVolts,
  measureResistance,
  measureVoltage,
  OVER_RANGE_OHMS,
  PROBE_OHMS,
  PROBE_VOLTS,
  type ContinuityReading,
  type OhmReading,
  type VoltReading,
} from './meter.js';

export {
  allowedShiftMs,
  compareLogs,
  DEFAULT_TOLERANCE,
  type Mismatch,
  type MismatchReason,
  type Tolerance,
} from './compare.js';

export {
  ANALOG_ACV_RANGES,
  ANALOG_DCV_RANGES,
  ANALOG_OHM_INTERNAL_OHMS,
  ANALOG_OHM_RANGES,
  applyTesterAction,
  createTesterState,
  DEFAULT_ANALOG_OHM_RANGE,
  DEFAULT_ANALOG_VOLT_RANGE,
  NEEDLE_FULL_SCALE_DEG,
  NEEDLE_TIME_CONSTANT_MS,
  ohmNeedleDeg,
  readTester,
  stepTester,
  TESTER_NO_PROBE_DISPLAY,
  TESTER_OFF_DISPLAY,
  TESTER_TICK_MS,
  voltNeedleDeg,
  voltRangesFor,
  withZeroAdjustError,
  ZERO_ADJUST_ERROR_RATIO,
  type AnalogOhmRange,
  type TesterAction,
  type TesterKind,
  type TesterMode,
  type TesterReading,
  type TesterState,
} from './tester.js';
